### ISSUE TITLE
papi_avail issues

### ISSUE THREAD

**Issue by david-barker** [UoB-HPC/GW4-Isambard#2]
papi_avail is hitting issues. e.g.
[ex-drbarker@login-01 ~]$ papi_avail
ibwarn: [98607] mad_rpc_open_port: can't open UMAD port ((null):2)
Failed to open '(null)' port '2'
[ex-drbarker@login-01 ~]$

**Comment by heaton-dev** [comment]
Not been reported since, will investigate if reported again
